import fs from 'node:fs';
const root='/opt/nalarin-content-work',read=n=>JSON.parse(fs.readFileSync(`${root}/${n}`,'utf8'));
const qs=read('questions.json'),ps=read('passages.json');fs.mkdirSync(`${root}/pilot-review`,{recursive:true});
const tasks=[];
for(const grade of [6,9]){const math=qs.filter(q=>q.grade===grade&&q.subject==='matematika');for(let i=0;i<math.length;i+=4)tasks.push({id:`math-${grade}-${i}`,grade,questions:math.slice(i,i+4)});for(const passage of ps.filter(p=>p.grade===grade))tasks.push({id:passage.id,grade,passage,questions:qs.filter(q=>q.stimulus_id===passage.id)});}
async function ask(prompt,payload){const r=await fetch(process.env.MITSUKO_BASE_URL+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+process.env.MITSUKO_API_KEY},body:JSON.stringify({model:'mitsuko',messages:[{role:'system',content:prompt},{role:'user',content:JSON.stringify(payload)}],max_tokens:1500,stream:false}),signal:AbortSignal.timeout(90000)});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();return JSON.parse(d.choices[0].message.content.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''));}
const same=(a,b)=>JSON.stringify(Array.isArray(a)?[...a].sort():Object.fromEntries(Object.entries(a||{}).sort()))===JSON.stringify(Array.isArray(b)?[...b].sort():Object.fromEntries(Object.entries(b||{}).sort()));
let i=0;await Promise.all(Array.from({length:2},async()=>{while(i<tasks.length){const t=tasks[i++],file=`${root}/pilot-review/${t.id}.json`;if(fs.existsSync(file)){const old=JSON.parse(fs.readFileSync(file,'utf8'));if(old.results.every(r=>r.passed&&t.questions.find(q=>q.id===r.id)?.version===r.version))continue;}try{
 const blind=await ask('Pecahkan soal TKA secara independen tanpa kunci. JSON saja {solutions:[{id,answer:["A"] atau {A:"Benar",B:"Salah",C:"Benar"},reason:"bukti/hitungan singkat maksimal 25 kata",issues:[]}]}. Semua opsi kategori diperiksa. MCMA pilih semua benar. Laporkan ambiguitas nyata.',{grade:t.grade,passage:t.passage?.text,questions:t.questions.map(q=>({id:q.id,type:q.type,stem:q.stem,options:q.options}))});
 const editorial=await ask('Periksa soal, kunci dan pembahasan berikut. JSON saja {reviews:[{id,approved:true atau false,issues:[]}]}. Periksa setiap alasan opsi dan bukti bacaan. Tolak hanya jika keliru, ambigu, data kurang, penjelasan kontradiktif; bukan masalah gaya. Tidak perlu menyalin soal atau penjelasan.',{grade:t.grade,passage:t.passage?.text,questions:t.questions.map(q=>({id:q.id,type:q.type,stem:q.stem,options:q.options,answer:q.answer,explanation:q.explanation}))});
 const results=t.questions.map(q=>{const b=blind.solutions?.find(s=>s.id===q.id),e=editorial.reviews?.find(s=>s.id===q.id);if(b&&q.type==='PGK_MCMA'&&!Array.isArray(b.answer)&&Object.values(b.answer).every(v=>['Benar','Salah'].includes(v))){b.raw_answer=b.answer;b.answer=Object.keys(b.answer).filter(k=>b.answer[k]==='Benar');}return {id:q.id,version:q.version,match:!!b&&same(b.answer,q.answer),blind:b,editorial:e,passed:!!b&&same(b.answer,q.answer)&&!b.issues?.length&&e?.approved===true&&!e.issues?.length};});
 fs.writeFileSync(file,JSON.stringify({reviewed_at:new Date().toISOString(),model:'mitsuko',results},null,2));console.log(JSON.stringify({task:t.id,passed:results.filter(r=>r.passed).length,total:results.length}));
 }catch(e){console.log(JSON.stringify({task:t.id,error:e.message}));}}}));
